name : My first Pipeline

on: [push , fork]

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "My first Github job"

        - name: List Files
          run: ls

        - name: Read File
          run: cat README.md
    
